# Ejercicios 

## Ejercicio 1


Disponemos de dos ficheros que contienen mediciones de temperatura y humedad relativa del aire en diferentes puntos de una zona geográfica. Si observamos los datos, se trata de una matriz de celdas (o píxeles) organizadas en filas y columnas (o una cuadrícula) en la que cada celda contiene un valor que representa cierta información. En este caso, la temperatura y la humedad relativa.

<!--La siguiente figura muestra un ejemplo de este tipo de datos. Se puede ver el formato de cuadrícula, donde cada celda recoge una temperatura. Este tipo de datos se puede visualizar usando distintos colores, lo que facilita el análisis.

<img src="./images/rasterTemp.jpg" alt="temperaturas" style="width: 700px;"/>
-->

* Las mediciones de temperatura de nuestra zona geográfica de estudio  se encuentran en el fichero [temperaturas.txt](./datos/temperaturas.txt)
* El fichero  [humedad.txt](./datos/humedad.txt) recoge la humedad relativa de los mismos puntos en la misma zona geográfica.



__a)__ Crear un array de `numpy` con los datos de las temperaturas de la zona geográfica de estudio. El array ha de llamarse `temperatura`.

   * Descarga el fichero  en tu directorio de trabajo.
   * Carga el fichero mediante la función `loadtxt`.  Usa el parámetro `dtype` para indicar que los valores sean de tipo `int`. Si tu sistema operativo es iOS, es probable que te de error si pones tipo `int`. Prueba a poner `float`.

In [12]:
# Sol:
import numpy as np
temperaturas = np.loadtxt("./datos/temperaturas.txt")

In [13]:
temperaturas

array([[16., 16., 15., ..., 18., 18., 18.],
       [18., 18., 18., ..., 22., 21., 21.],
       [22., 22., 22., ..., 19., 19., 19.],
       ...,
       [17., 17., 17., ..., 19., 19., 19.],
       [19., 19., 18., ..., 19., 19., 19.],
       [19., 20., 20., ..., 19., 19., 19.]])

__b)__ Crear un array de `numpy` con los datos de las mediciones de humedad de la zona geográfica de estudio. El array ha de llamarse `humedad`.

   * Descarga el fichero  en tu directorio de trabajo.
   * Carga el fichero mediante la función `loadtxt`.  Usa el parámetro `dtype` para indicar que los valores sean de tipo `float`.

In [14]:
# Sol:

humedad = np.loadtxt("./datos/humedad.txt")

In [15]:
humedad

array([[66.2, 66.1, 66.5, ..., 83.9, 83.8, 83.8],
       [83.7, 83.3, 83.4, ..., 78. , 78. , 77.9],
       [77.9, 77.9, 77.8, ..., 41.2, 41.2, 40.7],
       ...,
       [87.1, 87.1, 87.2, ..., 71.4, 71.3, 71.2],
       [71.3, 71.2, 70.8, ..., 58. , 58.5, 58.8],
       [58.8, 58.7, 57.2, ..., 44.6, 44.6, 44.9]])

__c)__ Determinar el tamaño de los datos. ¿Cuántas filas y cuántas columnas tiene el array `temperatura`?, ¿Cuantas filas y cuántas columnas tiene el array `humedad`?

In [16]:
# sol:
# Ambos arrays son del mismo tamaño, 133 filas y 133 columnas
temperaturas.shape

(133, 133)

__d)__ Calcula la temperatura máxima y mínima registrada.

In [28]:
# SOl: 
# temperatura máxima: 31
# temperatura máxima: 10

tmax = temperaturas.max()
tmin = temperaturas.min()
print (f"La temperatura máxima es {tmax} y la temperatura mínima es {tmin}")

La temperatura máxima es 31.0 y la temperatura mínima es 10.0


__e)__ El índice de temperatura-humedad, es un número utilizado para indicar la falta de confort causada por los efectos combinados de la temperatura y la humedad del aire. El índice fue desarrollado en 1959 por Earl C. Thom, un investigador de la Oficina de Climatología del US Weather Bureau.
La fórmula para calcular el índice de temperatura-humedad (ITH) es: 

$ITH = 0.8 \times temperatura  + \frac{humedad_{relativa}}{100} \times (temperatura - 14.3) + 46.4 $

Calcula el índice de temperatura-humedad (ITH) de cada una de las celdas de la cuadrícula. El resultado debe ser un array bidimensional con el mismo número de filas y columnas que los arrays `temperatura` y  `humedad`. El nombre de este array debe ser `ith`.

Para calcular el índice de temperatura humedad puedes seguir los siguientes pasos:
* (1) Multiplica el array temperatura por 0.8
* (2) Divide el array humedad por 100
* (3) Resta 14.3 al array temperatura
* (4) Multiplica el resultado de (2) por el resultado de (3)
* (5) Suma 46.4 al resultado de (4) 
* (6) Suma el resultado de (5) y el resultado de (1)


In [30]:
# Sol:

# ith = array([[60.3254, 60.3237, 58.8655, ..., 63.9043, 63.9006, 63.9006],
#            [63.8969, 63.8821, 63.8858, ..., 70.006 , 68.426 , 68.4193],
#            [69.9983, 69.9983, 69.9906, ..., 63.5364, 63.5364, 63.5129],
#            ...,
#            [62.3517, 62.3517, 62.3544, ..., 64.9558, 64.9511, 64.9464],
#            [64.9511, 64.9464, 63.4196, ..., 64.326 , 64.3495, 64.3636],
#            [64.3636, 65.7459, 65.6604, ..., 63.6962, 63.6962, 63.7103]])

ITH = 0.8*temperaturas+(humedad/100)*(temperaturas-14.3)+46.4
print (ITH)

[[60.3254 60.3237 58.8655 ... 63.9043 63.9006 63.9006]
 [63.8969 63.8821 63.8858 ... 70.006  68.426  68.4193]
 [69.9983 69.9983 69.9906 ... 63.5364 63.5364 63.5129]
 ...
 [62.3517 62.3517 62.3544 ... 64.9558 64.9511 64.9464]
 [64.9511 64.9464 63.4196 ... 64.326  64.3495 64.3636]
 [64.3636 65.7459 65.6604 ... 63.6962 63.6962 63.7103]]


In [31]:
ITH.shape

(133, 133)

__f)__ Redondea los valores del array obtenido en el apartado anterior (`ith`) al entero más cercano. Puedes usar la función universal `np.around`. Para obtener información de uso de la función `np.around` ejecuta la siguiente celda o consulta la ayuda en https://numpy.org/doc/stable/reference/generated/numpy.around.html

In [8]:
# ejecuta esta celda y busca el ejemplo de uso
np.around?

In [35]:
# Sol: 
#   ith = array([[60., 60., 59., ..., 64., 64., 64.],
#                   [64., 64., 64., ..., 70., 68., 68.],
#                   [70., 70., 70., ..., 64., 64., 64.],
#                   ...,
#                   [62., 62., 62., ..., 65., 65., 65.],
#                   [65., 65., 63., ..., 64., 64., 64.],
#                   [64., 66., 66., ..., 64., 64., 64.]])

np.around(ITH)

array([[60., 60., 59., ..., 64., 64., 64.],
       [64., 64., 64., ..., 70., 68., 68.],
       [70., 70., 70., ..., 64., 64., 64.],
       ...,
       [62., 62., 62., ..., 65., 65., 65.],
       [65., 65., 63., ..., 64., 64., 64.],
       [64., 66., 66., ..., 64., 64., 64.]])

__g)__ Calcula la media del índice de temperatura-humedad (ITH).

In [37]:
# Sol:
ITH.mean()

66.47344160777885

__h)__ En la actualidad este índice se utiliza para supervisar las condiciones de estrés por calor a las que está expuesto el ganado bovino, y su correlato en la producción lechera y su eficiencia reproductiva. En general los expertos han determinado que con un índice ITH inferior a 72 el ganado lechero no experimenta estrés, si el IHT se entre 72 y 78 el estrés es moderado y valores ITH de entre 78 y 88 se caracterizan por un estrés grave.

Determina si se produce estrés en algún punto de la cuadrícula, es decir, si existe algún valor mayor a 72. ¿Se produce estrés grave en algún punto?

In [44]:
# Sol:
# crear el filtro
filtro = ITH > 72
filtro2 = ITH < 78
estres = ITH[filtro & filtro2]
len(estres)

1737

__i)__ ¿En cuántos puntos de la cuadrícula se produce estrés grave?

In [45]:
filtro3 = ITH > 78
estres_grave = ITH[filtro3]
len(estres_grave)

786

__j)__ ¿Cuántos puntos tiene mi cuadrícula inicial?

In [46]:
ITH.size

17689

---------------------