# Ejercicios Numpy 4

Los enlaces que te encuentres en esta página, solo funcionan desde el formato html, no desde el notebook una vez descargado.

## Ejercicio 1

Dos niños están haciendo una colección de cromos. Cada cromo tiene asignado un número entero entre 1 y 200.

* Los cromos que tiene Juan se encuentran en el fichero [juan.txt](./datos/col_juan.txt). La primera columna representa el número asociado al cromo y la segunda columna representa el número de cromos con ese número que tiene Juan.

* Los cromos que tiene Pedro se encuentran en el fichero [pedro.txt](./datos/col_pedro.txt). La primera columna representa el número asociado al cromo y la segunda columna representa el número de cromos con ese número que tiene Pedro.

__a)__ Crear un array de `numpy` con los datos de cada una de las colecciones. Los arrays han de llamarse `juan`y `pedro`.

   * Descarga los ficheros  en tu directorio de trabajo.
   * Carga cada uno de los ficheros mediante la función `loadtxt`. Usa el parámetro  `delimiter` con valor `,`. Usa el parámetro `dtype` para indicar que los valores sean de tipo `int`. Si usas MAC, es posible que tengas que asignar el valor `float` al parámetro `dtype`.

In [1]:
# Sol: 
import numpy as np

In [10]:
juan = np.loadtxt("./datos/col_juan.txt", delimiter=',', dtype=int)
pedro = np.loadtxt("./datos/col_pedro.txt", delimiter=',', dtype=int)

C:\Users\Sergi\OneDrive\Documents\MPVD\Software\tmp\ipykernel_426668\1405328178.py:1: DeprecationWarning: loadtxt(): Parsing an integer via a float is deprecated.  To avoid this warning, you can:
    * make sure the original data is stored as integers.
    * use the `converters=` keyword argument.  If you only use
      NumPy 1.23 or later, `converters=float` will normally work.
    * Use `np.loadtxt(...).astype(np.int64)` parsing the file as
      floating point and then convert it.  (On all NumPy versions.)
  (Deprecated NumPy 1.23)
  juan = np.loadtxt("./datos/col_juan.txt", delimiter=',', dtype=int)
C:\Users\Sergi\OneDrive\Documents\MPVD\Software\tmp\ipykernel_426668\1405328178.py:2: DeprecationWarning: loadtxt(): Parsing an integer via a float is deprecated.  To avoid this warning, you can:
    * make sure the original data is stored as integers.
    * use the `converters=` keyword argument.  If you only use
      NumPy 1.23 or later, `converters=float` will normally work.
    * U

In [9]:
juan

array([[  2,   4],
       [  5,   5],
       [  8,  13],
       [ 15,  11],
       [ 25,   4],
       [ 28,  14],
       [ 31,  15],
       [ 33,  17],
       [ 37,   7],
       [ 40,   3],
       [ 41,   1],
       [ 42,   9],
       [ 43,   3],
       [ 49,   6],
       [ 53,   8],
       [ 54,  14],
       [ 57,  10],
       [ 60,  10],
       [ 61,   2],
       [ 62,  15],
       [ 67,   3],
       [ 68,   5],
       [ 70,  14],
       [ 71,  10],
       [ 74,   9],
       [ 80,  16],
       [ 90,   1],
       [ 97,  17],
       [105,  15],
       [108,  18],
       [110,  15],
       [111,   2],
       [112,   6],
       [116,   9],
       [117,   5],
       [123,  10],
       [127,  10],
       [130,  17],
       [132,   3],
       [133,   4],
       [134,   7],
       [135,   9],
       [137,  14],
       [142,   7],
       [143,  10],
       [144,   3],
       [145,  15],
       [148,   3],
       [152,  11],
       [153,   5],
       [157,  10],
       [158,  12],
       [159,

In [11]:
pedro

array([[  2,   4],
       [  4,   1],
       [  6,   9],
       [  7,   4],
       [  9,  10],
       [ 10,  10],
       [ 11,  10],
       [ 13,  10],
       [ 14,  19],
       [ 15,   5],
       [ 18,  16],
       [ 19,  14],
       [ 20,  13],
       [ 22,  17],
       [ 23,   9],
       [ 24,  15],
       [ 26,  14],
       [ 27,  11],
       [ 28,  10],
       [ 29,  17],
       [ 31,   1],
       [ 32,   9],
       [ 35,  18],
       [ 36,   1],
       [ 39,  10],
       [ 40,  12],
       [ 42,  12],
       [ 43,  14],
       [ 44,   6],
       [ 47,   6],
       [ 49,   4],
       [ 50,  11],
       [ 51,  13],
       [ 53,  16],
       [ 54,   9],
       [ 56,  10],
       [ 58,  16],
       [ 59,  14],
       [ 60,  14],
       [ 61,  16],
       [ 63,   3],
       [ 64,   5],
       [ 65,   5],
       [ 68,  11],
       [ 71,  18],
       [ 73,   8],
       [ 74,  11],
       [ 77,  13],
       [ 78,  13],
       [ 79,  16],
       [ 80,   3],
       [ 83,  10],
       [ 84,

__b)__ Calcula el número de cromos diferentes que tiene cada niño. 

In [12]:
# SOl: 
# juan tiene 68 cromos
# pedro tiene 124 cromos
len(pedro), len(juan)

(124, 68)

__c)__ Calcula el número de cromos totales que tiene cada niño (contando los cromos repetidos). 

In [14]:
# SOl: 
# pedro tiene 1326 cromos 
# juan tiene 619 cromos
np.sum(pedro[:,1])

1326

In [15]:
pedro[:,1].sum()

1326

In [16]:
juan[:,1].sum()

619

__d)__ Calcula el número de cromos que aparecen en las dos colecciones. Puedes usar la función `np.intersect1d`.

In [19]:
# Sol
# Hay 44 cromos que aparecen en las dos colecciones
repetidos = np.intersect1d(pedro[:,0], juan[:,0])
len(repetidos)

44

__e)__ Entre los dos niños, ¿forman la colección completa?. Puedes usar la función `np.union1d`.

In [21]:
# Sol: 
# No Forman la colección completa. Entre los dos, solo tienen 148 cromos distintos y la colección tiene 200 cromos
union = np.union1d(pedro[:,0], juan[:,0])
len(union)

148

In [22]:
np.union1d?

__f)__ ¿Qué números faltan para tener la colección completa?

* Puedes generar un array de todos los cromos de la colección con la función `arange`.
* Usa la función `np.in1d` 

In [23]:
# Sol:
# Listado de los cromos que faltan:
#      [  1,   3,  12,  16,  17,  21,  30,  34,  38,  45,  46,  48,  52,
#        55,  66,  69,  72,  75,  76,  81,  82,  91,  92,  96, 100, 106,
#       107, 113, 114, 119, 122, 124, 125, 129, 138, 139, 140, 146, 151,
#       154, 155, 173, 176, 180, 181, 184, 185, 186, 190, 194, 199, 200]
    
completa = np.arange(1,201)
completa

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103, 104,
       105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117,
       118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130,
       131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143,
       144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156,
       157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169,
       170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 18

In [30]:
filtro_faltan = np.in1d(completa,union,invert=True)

In [31]:
completa[filtro_faltan]

array([  1,   3,  12,  16,  17,  21,  30,  34,  38,  45,  46,  48,  52,
        55,  66,  69,  72,  75,  76,  81,  82,  91,  92,  96, 100, 106,
       107, 113, 114, 119, 122, 124, 125, 129, 138, 139, 140, 146, 151,
       154, 155, 173, 176, 180, 181, 184, 185, 186, 190, 194, 199, 200])

__g)__ Calcula el cromo más repetido de juan. Usa la función `np.argmax`.

In [32]:
# Sol (166)
np.argmax(juan[:,1])

56

In [33]:
juan[56]

array([166,  19])

__h)__ Calcula el número de cromos de la colección de Juan con más de 10 repeticiones.

In [35]:
# Sol:
# (Juan tiene 26 cromos con más 10 repeticiones)
filtro_10 = pedro[:,1] > 10
pedro[filtro_10]

array([[ 14,  19],
       [ 18,  16],
       [ 19,  14],
       [ 20,  13],
       [ 22,  17],
       [ 24,  15],
       [ 26,  14],
       [ 27,  11],
       [ 29,  17],
       [ 35,  18],
       [ 40,  12],
       [ 42,  12],
       [ 43,  14],
       [ 50,  11],
       [ 51,  13],
       [ 53,  16],
       [ 58,  16],
       [ 59,  14],
       [ 60,  14],
       [ 61,  16],
       [ 68,  11],
       [ 71,  18],
       [ 74,  11],
       [ 77,  13],
       [ 78,  13],
       [ 79,  16],
       [ 84,  13],
       [ 85,  12],
       [ 86,  17],
       [ 87,  18],
       [ 88,  18],
       [ 89,  12],
       [ 93,  15],
       [ 94,  14],
       [ 95,  14],
       [ 97,  17],
       [ 98,  14],
       [ 99,  11],
       [101,  19],
       [102,  19],
       [109,  11],
       [112,  14],
       [115,  13],
       [120,  16],
       [123,  14],
       [131,  17],
       [134,  18],
       [143,  15],
       [145,  17],
       [149,  12],
       [157,  15],
       [163,  13],
       [164,

__i)__ Calcula el número de cromos con más de 10 repeticiones.


In [16]:
# Sol:
#  los crmos de la colección de Juan con más de 10 repeticiones son:
#  [  8,  15,  28,  31,  33,  54,  62,  70,  80,  97, 105, 108, 110,
#       130, 137, 145, 152, 158, 160, 166, 167, 170, 171, 172, 178, 197]


__j)__ Averigüa los números de los cromos que le faltan a Pedro para acabar la colección.

In [17]:
# Sol:
#      [  1,   3,   4,   6,   7,   9,  10,  11,  12,  13,  14,  16,  17,
#        18,  19,  20,  21,  22,  23,  24,  26,  27,  29,  30,  32,  34,
#        35,  36,  38,  39,  44,  45,  46,  47,  48,  50,  51,  52,  55,
#        ....,
#       181, 184, 185, 186, 187, 188, 189, 190, 191, 193, 194, 195, 196,
#       199, 200]


__k)__ Cuántos cromos tienen entre los dos niños

In [18]:
# Sol: 1945 cromos


__l)__ Calcula el cromo  de Pedro que se repite menos veces

In [36]:
# Sol: el cromo 4
np.min(pedro[:,1])

1

---------------------

In [38]:
filtro_1=pedro[:,1]==1
pedro[filtro_1]

array([[  4,   1],
       [ 31,   1],
       [ 36,   1],
       [117,   1],
       [196,   1]])